# Generated by Django 4.1.6 on 2023-08-14 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField(choices=[(1, 'No puedo Entrar'), (2, 'No aparece mi Evento'), (3, 'Otros')])),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'paises'},
        ),
    ]
